### ISSUE TITLE
micalevisk/last-issue-action@v2 not found

### ISSUE THREAD

**Issue by andrew-saydjari** [micalevisk/last-issue-action#12]
As of 3 days ago, micalevisk/last-issue-action@v2 is returning "not found" for me in one of my GitHub workflows. I have tried changing this from v2 to v2.0.0 and v2.2.0 (which appears to not be in the marketplace), as well as direct harsh specifications of both of those releases, all of which return "not found." This error starting simultaneously with the v2.2.0 release makes me suspect something occurred in that process to break the action/rename it somehow. An example of the failure is [here](https://github.com/andrew-saydjari/andrew-saydjari.github.io/actions/runs/6788990048/job/18455189158), where the run history shows the first failure date.

**Comment by micalevisk** [comment]
thank you for reporting!

I believe that this was a regression on v2.2

Can you please try `v2.1.0` instead? I'll revert that ASAP

**Comment by andrew-saydjari** [comment]
Confirmed, reverting to v2.1.0 (by specifying explicitly) has solved the issue for me.

**Comment by micalevisk** [comment]
@andrew-saydjari v2 should be working now

I was trying to support GH enterprise but it didn't work

**Comment by andrew-saydjari** [comment]
Can I use this goodwill to ask you to look at https://github.com/andrew-saydjari/andrew-saydjari.github.io/issues (this is my personal website, but I have several other applications I want to extend to if I can get this working) where #84 was created instead of appending to #83? I feel like my usage [here](https://github.com/andrew-saydjari/andrew-saydjari.github.io/blob/master/.github/workflows/linkCheck.yml) is a perfect mirror to your example, but just isn't working for me.

<blockquote><img src="https://opengraph.githubassets.com/0bc5fc0fffc5b015c4a924fd3bb09033134ea73acfc3a637d47408c7b1e088d6/andrew-saydjari/andrew-saydjari.github.io" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/andrew-saydjari/andrew-saydjari.github.io">Issues · andrew-saydjari/andrew-saydjari.github.io</a></strong></div><div>Personal Academic Website. Contribute to andrew-saydjari/andrew-saydjari.github.io development by creating an account on GitHub.</div></blockquote>

**Comment by micalevisk** [comment]
it worked locally, at least :thinking: 

![image](https://github.com/micalevisk/last-issue-action/assets/13461315/3340004c-e154-4c5e-ba6f-577fb8be0365)


run the action again with the debug mode, please

**Comment by andrew-saydjari** [comment]
https://github.com/andrew-saydjari/andrew-saydjari.github.io/actions/runs/6791129291/job/18461996780

it looks like issue-number is null, despite being found has-found being true?

<blockquote><img src="https://opengraph.githubassets.com/0bc5fc0fffc5b015c4a924fd3bb09033134ea73acfc3a637d47408c7b1e088d6/andrew-saydjari/andrew-saydjari.github.io" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/andrew-saydjari/andrew-saydjari.github.io">Links · andrew-saydjari/andrew-saydjari.github.io@ec82e2a</a></strong></div><div>Personal Academic Website. Contribute to andrew-saydjari/andrew-saydjari.github.io development by creating an account on GitHub.</div></blockquote>

**Comment by andrew-saydjari** [comment]
(I am happy to split this off into a new issue if there really is something to track down, but my first assumption was that I had some silly typo)

**Comment by micalevisk** [comment]
oh you're using `issue_number` instead of `issue-number`

**Comment by andrew-saydjari** [comment]
Yes. Thank you for finding my stupid typo. Everything looks great now, I am a happy user, and will proliferate my usage! 👍🏽
