### ISSUE TITLE
Purpose of `limit: 1`?

### ISSUE THREAD

**Issue by polarathene** [micalevisk/last-issue-action#3]
https://github.com/micalevisk/last-issue-action/blob/a779b00cf9770e42a5ff23207d40c68a3f02a94f/src/core.ts#L34

I can't seem to lookup the `limit` parameter being set here. What was the purpose of it? Is it an actual parameter documented somewhere? `per_page: 1` already limits the results to 1 and the default page is 1.

- https://docs.github.com/en/rest/issues/issues#list-repository-issues
- https://octokit.github.io/rest.js/v18#issues-list-for-repo

**Comment by micalevisk** [comment]
yeah, that value is useless
